"""Event identity helpers.

Event IDs are generated by the client and are the idempotency key for
ingestion (``docs/sdd.md`` section 7.4). The server therefore *validates*
incoming IDs and never mints one for a submitted event: a server-minted ID
would make a retried batch look like new work.

:func:`derive_event_id` exists only for fixtures and the ``eval/`` scenarios,
where a stable ID must be reproducible from the scenario definition instead of
being drawn at random.
"""

from __future__ import annotations

import re
import uuid
from typing import Final

from .errors import INVALID_INPUT, ServiceError

#: Namespace for deterministic synthetic identifiers. Fixed so that scenario
#: output is byte-identical across machines and runs.
SYNTHETIC_NAMESPACE: Final = uuid.UUID("4f2b5a0e-2c1d-4c2a-9f0a-6f4ba9b1d3e7")

_UUID_PATTERN: Final = re.compile(
    r"\A[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\Z"
)


def is_event_id(value: object) -> bool:
    """Return whether ``value`` is a canonical lowercase UUID string."""
    return isinstance(value, str) and bool(_UUID_PATTERN.match(value))


def require_event_id(value: object, *, field: str = "eventId") -> str:
    """Validate a client-supplied identifier, or raise ``invalid_input``."""
    if not is_event_id(value):
        raise ServiceError(
            INVALID_INPUT,
            "malformed_identifier",
            detail={"field": field, "value": value if isinstance(value, str) else None},
        )
    return value  # type: ignore[return-value]


def derive_event_id(*parts: object) -> str:
    """Derive a stable synthetic event ID from ``parts``.

    For fixtures and synthetic scenarios only. Production clients generate
    random UUIDs; deriving IDs from content in production would collapse two
    genuinely distinct reports that happen to share a payload.
    """
    key = "\x1f".join(str(part) for part in parts)
    return str(uuid.uuid5(SYNTHETIC_NAMESPACE, key))
