"""AED ingestion, candidate search, routing, and reassignment services."""

from .assignment import (
    AedAssignment,
    AedAssignmentService,
    AssignmentStatus,
    AssignmentStore,
    InMemoryAssignmentStore,
    ReassignmentOutcome,
    ReassignmentResult,
    UnavailabilityReport,
)
from .availability import AvailabilityAssessment, evaluate_availability
from .candidates import (
    AedCandidate,
    CandidateSearchConfig,
    CandidateSearchResult,
    find_candidates,
    rank_candidates,
)
from .catalog import AedCatalogService
from .geo import BoundingBox, bounding_box, haversine_meters
from .helpers import (
    HelperLocationConfig,
    HelperLocationStatus,
    HelperPosition,
    LocationFreshness,
    ProximityAssessment,
    assess_proximity,
    evaluate_helper_location,
)
from .retrieval import (
    RetrievalAssumption,
    RetrievalEstimate,
    estimate_remaining_after_collection,
    estimate_retrieval,
)
from .routing import (
    DeterministicFakeRouteProvider,
    GoogleRoutesProvider,
    HttpRequest,
    HttpResponse,
    RouteEstimate,
    RouteEstimateConfig,
    RouteEstimateSource,
    RouteFreshness,
    RouteLeg,
    RouteProvider,
    RouteProviderError,
    estimate_walking_route,
    straight_line_estimate,
)

__all__ = [
    "AedAssignment",
    "AedAssignmentService",
    "AedCandidate",
    "AedCatalogService",
    "AssignmentStatus",
    "AssignmentStore",
    "AvailabilityAssessment",
    "BoundingBox",
    "CandidateSearchConfig",
    "CandidateSearchResult",
    "DeterministicFakeRouteProvider",
    "GoogleRoutesProvider",
    "HelperLocationConfig",
    "HelperLocationStatus",
    "HelperPosition",
    "HttpRequest",
    "HttpResponse",
    "InMemoryAssignmentStore",
    "LocationFreshness",
    "ProximityAssessment",
    "ReassignmentOutcome",
    "ReassignmentResult",
    "RetrievalAssumption",
    "RetrievalEstimate",
    "RouteEstimate",
    "RouteEstimateConfig",
    "RouteEstimateSource",
    "RouteFreshness",
    "RouteLeg",
    "RouteProvider",
    "RouteProviderError",
    "UnavailabilityReport",
    "assess_proximity",
    "bounding_box",
    "estimate_remaining_after_collection",
    "estimate_retrieval",
    "estimate_walking_route",
    "evaluate_availability",
    "evaluate_helper_location",
    "find_candidates",
    "haversine_meters",
    "rank_candidates",
    "straight_line_estimate",
]
