from __future__ import annotations

from typing import Protocol
from uuid import UUID

from app.schemas.contracts import (
    AedListResponse, CreateIncidentRequest, CreateShareRequest, CreateShareResponse,
    EventBatchRequest, EventBatchResponse, HandoffEventsResponse, HelperUpdateRequest,
    HelperUpdateResponse, IncidentView, LocationDescriptionRequest,
    LocationDescriptionResponse, PatchIncidentRequest, SceneObservationRequest,
    SceneObservationResponse, SceneSnapshotResponse, ShareSessionRequest, ShareSessionResponse,
    RevokeAccessRequest, RevokeAccessResponse,
)


class IncidentService(Protocol):
    """Workstream 5 implements this interface with persistent, scoped services."""

    def create_incident(self, uid: str, body: CreateIncidentRequest) -> IncidentView: ...
    def authorize(self, uid: str, incident_id: UUID, scopes: set[str], helper_id: UUID | None = None) -> IncidentView: ...
    def upload_events(self, uid: str, incident_id: UUID, body: EventBatchRequest) -> EventBatchResponse: ...
    def add_observations(self, uid: str, incident_id: UUID, body: SceneObservationRequest) -> SceneObservationResponse: ...
    def describe_location(self, uid: str, incident_id: UUID, body: LocationDescriptionRequest) -> LocationDescriptionResponse: ...
    def create_share(self, uid: str, incident_id: UUID, body: CreateShareRequest) -> CreateShareResponse: ...
    def revoke_access(self, uid: str, incident_id: UUID, body: RevokeAccessRequest) -> RevokeAccessResponse: ...
    def exchange_share(self, uid: str, body: ShareSessionRequest) -> ShareSessionResponse: ...
    def update_helper(self, uid: str, incident_id: UUID, helper_id: UUID, body: HelperUpdateRequest) -> HelperUpdateResponse: ...
    def list_aeds(self, uid: str, incident_id: UUID, limit: int, *, lat: float | None = None, lng: float | None = None) -> AedListResponse: ...
    def get_snapshot(self, uid: str, incident_id: UUID) -> SceneSnapshotResponse: ...
    def handoff_events(self, uid: str, incident_id: UUID, cursor: str | None, limit: int) -> HandoffEventsResponse: ...
    def patch_incident(self, uid: str, incident_id: UUID, body: PatchIncidentRequest) -> IncidentView: ...
